on:
  push:
    branches: [main, master]
    
name: shinylive-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages  # Added this line to specify the environment
      
    steps:
      - uses: actions/checkout@v4
      
      # Set up R
      - uses: r-lib/actions/setup-r@v2
      
      - name: "Setup R dependency for Shinylive App export"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            cran::shinylive
            cran::jsonlite
      
       # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export app
        run: |
          shinylive::export(".", "_site")
        shell: Rscript {0}
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with: 
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
